<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.2.1
 */
echo '<pre>'.print_r(array_column($COLUMNS, 'COLUMN_TYPE'),1).'</pre>';

//function parseType(string $type): array|string {
//	$unsigned = false;
//	if(\str_ends_with($type, ' unsigned')){
//		//$this->unsigned = true;
//		$unsigned = true;
//		//$this->params = array_filter($this->params, fn($param) =>
//		$params = array_filter($params, fn($param) =>
//			strtoupper($param) !== 'UNSIGNED'
//		);
//	}
//	if (preg_match('/^(\w+)(?:\((.*?)\))?$/', strtoupper($type), $matches)) {
//		//$this->type = $matches[1];
//		$type = $matches[1];
//		//$this->params = isset($matches[2]) ? array_map('trim', explode(',', $matches[2])) : [];
//		$params = isset($matches[2])
//			? array_map('trim', explode(',', $matches[2]))
//			: [];
//		//! test return added
//		return [
//			'type' => $type,
//			'params' => $params,
//			'unsigned' => $unsigned,
//		];
//	} else {
//		return '"'.$type.'" type was not found..';
//		//throw new ValException(
//		//	"Invalid type format: {type}",
//		//	'invalid_type_format',
//		//	['type' => $type]
//		//);
//	}
//}
//
//foreach($COLUMNS as $ary){
//	$results[] = parseType($ary['COLUMN_TYPE']);
//}
//print_r($results);
/**
 * Database `information_schema`
 *
 * This is just an example of a database table with almost every type of column available
 *  I used this to kind of help building to MySQLCheck class
 *  `information_schema`.`COLUMNS`
 */
$COLUMNS = [
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'id',
		'ORDINAL_POSITION' => '1',
		'COLUMN_DEFAULT' => NULL,
		'IS_NULLABLE' => 'NO',
		'DATA_TYPE' => 'bigint',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => '20',
		'NUMERIC_SCALE' => '0',
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'bigint unsigned',
		'COLUMN_KEY' => 'PRI',
		'EXTRA' => 'auto_increment',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'TINYINT_COL',
		'ORDINAL_POSITION' => '2',
		'COLUMN_DEFAULT' => '0',
		'IS_NULLABLE' => 'NO',
		'DATA_TYPE' => 'tinyint',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => '3',
		'NUMERIC_SCALE' => '0',
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'tinyint',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'SMALLINT_COL',
		'ORDINAL_POSITION' => '3',
		'COLUMN_DEFAULT' => '0',
		'IS_NULLABLE' => 'NO',
		'DATA_TYPE' => 'smallint',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => '5',
		'NUMERIC_SCALE' => '0',
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'smallint',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'MEDIUMINT_COL',
		'ORDINAL_POSITION' => '4',
		'COLUMN_DEFAULT' => '0',
		'IS_NULLABLE' => 'NO',
		'DATA_TYPE' => 'mediumint',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => '7',
		'NUMERIC_SCALE' => '0',
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'mediumint',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'INT_COL',
		'ORDINAL_POSITION' => '5',
		'COLUMN_DEFAULT' => '0',
		'IS_NULLABLE' => 'NO',
		'DATA_TYPE' => 'int',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => '10',
		'NUMERIC_SCALE' => '0',
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'int',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'BIGINT_COL',
		'ORDINAL_POSITION' => '6',
		'COLUMN_DEFAULT' => '0',
		'IS_NULLABLE' => 'NO',
		'DATA_TYPE' => 'bigint',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => '19',
		'NUMERIC_SCALE' => '0',
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'bigint',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'DECIMAL_COL',
		'ORDINAL_POSITION' => '7',
		'COLUMN_DEFAULT' => '0.00',
		'IS_NULLABLE' => 'NO',
		'DATA_TYPE' => 'decimal',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => '10',
		'NUMERIC_SCALE' => '2',
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'decimal(10,2)',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'FLOAT_COL',
		'ORDINAL_POSITION' => '8',
		'COLUMN_DEFAULT' => '0',
		'IS_NULLABLE' => 'NO',
		'DATA_TYPE' => 'float',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => '12',
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'float',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'DOUBLE_COL',
		'ORDINAL_POSITION' => '9',
		'COLUMN_DEFAULT' => '0',
		'IS_NULLABLE' => 'NO',
		'DATA_TYPE' => 'double',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => '22',
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'double',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'REAL_COL',
		'ORDINAL_POSITION' => '10',
		'COLUMN_DEFAULT' => '0',
		'IS_NULLABLE' => 'NO',
		'DATA_TYPE' => 'double',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => '22',
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'double',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'BIT_COL',
		'ORDINAL_POSITION' => '11',
		'COLUMN_DEFAULT' => 'b\'0\'',
		'IS_NULLABLE' => 'NO',
		'DATA_TYPE' => 'bit',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => '1',
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'bit(1)',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'BOOL_COL',
		'ORDINAL_POSITION' => '12',
		'COLUMN_DEFAULT' => '0',
		'IS_NULLABLE' => 'NO',
		'DATA_TYPE' => 'tinyint',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => '3',
		'NUMERIC_SCALE' => '0',
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'tinyint(1)',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'BOOLEAN_COL',
		'ORDINAL_POSITION' => '13',
		'COLUMN_DEFAULT' => '0',
		'IS_NULLABLE' => 'NO',
		'DATA_TYPE' => 'tinyint',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => '3',
		'NUMERIC_SCALE' => '0',
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'tinyint(1)',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'DATE_COL',
		'ORDINAL_POSITION' => '14',
		'COLUMN_DEFAULT' => NULL,
		'IS_NULLABLE' => 'YES',
		'DATA_TYPE' => 'date',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'date',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'DATETIME_COL',
		'ORDINAL_POSITION' => '15',
		'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
		'IS_NULLABLE' => 'YES',
		'DATA_TYPE' => 'datetime',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => '0',
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'datetime',
		'COLUMN_KEY' => '',
		'EXTRA' => 'DEFAULT_GENERATED',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'TIMESTAMP_COL',
		'ORDINAL_POSITION' => '16',
		'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
		'IS_NULLABLE' => 'NO',
		'DATA_TYPE' => 'timestamp',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => '0',
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'timestamp',
		'COLUMN_KEY' => '',
		'EXTRA' => 'DEFAULT_GENERATED',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'TIME_COL',
		'ORDINAL_POSITION' => '17',
		'COLUMN_DEFAULT' => '00:00:00',
		'IS_NULLABLE' => 'YES',
		'DATA_TYPE' => 'time',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => '0',
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'time',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'YEAR_COL',
		'ORDINAL_POSITION' => '18',
		'COLUMN_DEFAULT' => '2000',
		'IS_NULLABLE' => 'YES',
		'DATA_TYPE' => 'year',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'year',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'CHAR_COL',
		'ORDINAL_POSITION' => '19',
		'COLUMN_DEFAULT' => '',
		'IS_NULLABLE' => 'NO',
		'DATA_TYPE' => 'char',
		'CHARACTER_MAXIMUM_LENGTH' => '255',
		'CHARACTER_OCTET_LENGTH' => '1020',
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => 'utf8mb4',
		'COLLATION_NAME' => 'utf8mb4_unicode_ci',
		'COLUMN_TYPE' => 'char(255)',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'VARCHAR_COL',
		'ORDINAL_POSITION' => '20',
		'COLUMN_DEFAULT' => '',
		'IS_NULLABLE' => 'NO',
		'DATA_TYPE' => 'varchar',
		'CHARACTER_MAXIMUM_LENGTH' => '255',
		'CHARACTER_OCTET_LENGTH' => '1020',
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => 'utf8mb4',
		'COLLATION_NAME' => 'utf8mb4_unicode_ci',
		'COLUMN_TYPE' => 'varchar(255)',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'TINYTEXT_COL',
		'ORDINAL_POSITION' => '21',
		'COLUMN_DEFAULT' => NULL,
		'IS_NULLABLE' => 'YES',
		'DATA_TYPE' => 'tinytext',
		'CHARACTER_MAXIMUM_LENGTH' => '255',
		'CHARACTER_OCTET_LENGTH' => '255',
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => 'utf8mb4',
		'COLLATION_NAME' => 'utf8mb4_unicode_ci',
		'COLUMN_TYPE' => 'tinytext',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'TEXT_COL',
		'ORDINAL_POSITION' => '22',
		'COLUMN_DEFAULT' => NULL,
		'IS_NULLABLE' => 'YES',
		'DATA_TYPE' => 'text',
		'CHARACTER_MAXIMUM_LENGTH' => '65535',
		'CHARACTER_OCTET_LENGTH' => '65535',
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => 'utf8mb4',
		'COLLATION_NAME' => 'utf8mb4_unicode_ci',
		'COLUMN_TYPE' => 'text',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'MEDIUMTEXT_COL',
		'ORDINAL_POSITION' => '23',
		'COLUMN_DEFAULT' => NULL,
		'IS_NULLABLE' => 'YES',
		'DATA_TYPE' => 'mediumtext',
		'CHARACTER_MAXIMUM_LENGTH' => '16777215',
		'CHARACTER_OCTET_LENGTH' => '16777215',
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => 'utf8mb4',
		'COLLATION_NAME' => 'utf8mb4_unicode_ci',
		'COLUMN_TYPE' => 'mediumtext',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'LONGTEXT_COL',
		'ORDINAL_POSITION' => '24',
		'COLUMN_DEFAULT' => NULL,
		'IS_NULLABLE' => 'YES',
		'DATA_TYPE' => 'longtext',
		'CHARACTER_MAXIMUM_LENGTH' => '4294967295',
		'CHARACTER_OCTET_LENGTH' => '4294967295',
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => 'utf8mb4',
		'COLLATION_NAME' => 'utf8mb4_unicode_ci',
		'COLUMN_TYPE' => 'longtext',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'BINARY_COL',
		'ORDINAL_POSITION' => '25',
		'COLUMN_DEFAULT' => '0x',
		'IS_NULLABLE' => 'NO',
		'DATA_TYPE' => 'binary',
		'CHARACTER_MAXIMUM_LENGTH' => '255',
		'CHARACTER_OCTET_LENGTH' => '255',
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'binary(255)',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'VARBINARY_COL',
		'ORDINAL_POSITION' => '26',
		'COLUMN_DEFAULT' => '',
		'IS_NULLABLE' => 'NO',
		'DATA_TYPE' => 'varbinary',
		'CHARACTER_MAXIMUM_LENGTH' => '255',
		'CHARACTER_OCTET_LENGTH' => '255',
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'varbinary(255)',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'TINYBLOB_COL',
		'ORDINAL_POSITION' => '27',
		'COLUMN_DEFAULT' => NULL,
		'IS_NULLABLE' => 'YES',
		'DATA_TYPE' => 'tinyblob',
		'CHARACTER_MAXIMUM_LENGTH' => '255',
		'CHARACTER_OCTET_LENGTH' => '255',
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'tinyblob',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'BLOB_COL',
		'ORDINAL_POSITION' => '28',
		'COLUMN_DEFAULT' => NULL,
		'IS_NULLABLE' => 'YES',
		'DATA_TYPE' => 'blob',
		'CHARACTER_MAXIMUM_LENGTH' => '65535',
		'CHARACTER_OCTET_LENGTH' => '65535',
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'blob',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'MEDIUMBLOB_COL',
		'ORDINAL_POSITION' => '29',
		'COLUMN_DEFAULT' => NULL,
		'IS_NULLABLE' => 'YES',
		'DATA_TYPE' => 'mediumblob',
		'CHARACTER_MAXIMUM_LENGTH' => '16777215',
		'CHARACTER_OCTET_LENGTH' => '16777215',
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'mediumblob',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'LONGBLOB_COL',
		'ORDINAL_POSITION' => '30',
		'COLUMN_DEFAULT' => NULL,
		'IS_NULLABLE' => 'YES',
		'DATA_TYPE' => 'longblob',
		'CHARACTER_MAXIMUM_LENGTH' => '4294967295',
		'CHARACTER_OCTET_LENGTH' => '4294967295',
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'longblob',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'ENUM_COL',
		'ORDINAL_POSITION' => '31',
		'COLUMN_DEFAULT' => 'value1',
		'IS_NULLABLE' => 'NO',
		'DATA_TYPE' => 'enum',
		'CHARACTER_MAXIMUM_LENGTH' => '6',
		'CHARACTER_OCTET_LENGTH' => '24',
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => 'utf8mb4',
		'COLLATION_NAME' => 'utf8mb4_unicode_ci',
		'COLUMN_TYPE' => 'enum(\'value1\',\'value2\',\'value3\')',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'SET_COL',
		'ORDINAL_POSITION' => '32',
		'COLUMN_DEFAULT' => NULL,
		'IS_NULLABLE' => 'YES',
		'DATA_TYPE' => 'set',
		'CHARACTER_MAXIMUM_LENGTH' => '20',
		'CHARACTER_OCTET_LENGTH' => '80',
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => 'utf8mb4',
		'COLLATION_NAME' => 'utf8mb4_unicode_ci',
		'COLUMN_TYPE' => 'set(\'value1\',\'value2\',\'value3\')',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'GEOMETRY_COL',
		'ORDINAL_POSITION' => '33',
		'COLUMN_DEFAULT' => NULL,
		'IS_NULLABLE' => 'YES',
		'DATA_TYPE' => 'geometry',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'geometry',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'GEOMETRYCOLLECTION_COL',
		'ORDINAL_POSITION' => '34',
		'COLUMN_DEFAULT' => NULL,
		'IS_NULLABLE' => 'YES',
		'DATA_TYPE' => 'geomcollection',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'geomcollection',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'MULTILINESTRING_COL',
		'ORDINAL_POSITION' => '35',
		'COLUMN_DEFAULT' => NULL,
		'IS_NULLABLE' => 'YES',
		'DATA_TYPE' => 'multilinestring',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'multilinestring',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'MULTIPOINT_COL',
		'ORDINAL_POSITION' => '36',
		'COLUMN_DEFAULT' => NULL,
		'IS_NULLABLE' => 'YES',
		'DATA_TYPE' => 'multipoint',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'multipoint',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'MULTIPOLYGON_COL',
		'ORDINAL_POSITION' => '37',
		'COLUMN_DEFAULT' => NULL,
		'IS_NULLABLE' => 'YES',
		'DATA_TYPE' => 'multipolygon',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'multipolygon',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'POINT_COL',
		'ORDINAL_POSITION' => '38',
		'COLUMN_DEFAULT' => NULL,
		'IS_NULLABLE' => 'YES',
		'DATA_TYPE' => 'point',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'point',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'LINESTRING_COL',
		'ORDINAL_POSITION' => '39',
		'COLUMN_DEFAULT' => NULL,
		'IS_NULLABLE' => 'YES',
		'DATA_TYPE' => 'linestring',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'linestring',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'POLYGON_COL',
		'ORDINAL_POSITION' => '40',
		'COLUMN_DEFAULT' => NULL,
		'IS_NULLABLE' => 'YES',
		'DATA_TYPE' => 'polygon',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'polygon',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => NULL
	],
	[
		'TABLE_CATALOG' => 'def',
		'TABLE_SCHEMA' => '2025_db_tester',
		'TABLE_NAME' => 'datatypes_tweaked',
		'COLUMN_NAME' => 'JSON_COL',
		'ORDINAL_POSITION' => '41',
		'COLUMN_DEFAULT' => NULL,
		'IS_NULLABLE' => 'YES',
		'DATA_TYPE' => 'json',
		'CHARACTER_MAXIMUM_LENGTH' => NULL,
		'CHARACTER_OCTET_LENGTH' => NULL,
		'NUMERIC_PRECISION' => NULL,
		'NUMERIC_SCALE' => NULL,
		'DATETIME_PRECISION' => NULL,
		'CHARACTER_SET_NAME' => NULL,
		'COLLATION_NAME' => NULL,
		'COLUMN_TYPE' => 'json',
		'COLUMN_KEY' => '',
		'EXTRA' => '',
		'PRIVILEGES' => 'select,insert,update,references',
		'COLUMN_COMMENT' => '',
		'GENERATION_EXPRESSION' => '',
		'SRS_ID' => null
	],
];
